### ISSUE TITLE
Tiddlers with more than one link show up twice in backlinks

### ISSUE THREAD

**Issue by jdlrobson** [tiddlyweb/tiddlywebplugins.links#1]
Create a tiddler Bar with text

```
[[Foo]] [[Foo]]
```

Navigate to the tiddler Foo url that provides backlinks
- note the tiddler Bar appears twice
  It should only appear once.

**Comment by cdent** [comment]
I've fixed this for pages that are edited from the fix onward. Existing pages that have not been edited recently will not get the fix as the data is already in the database twice.
