### ISSUE TITLE
Intraspace links lead to 404s in TiddlySpace

### ISSUE THREAD

**Issue by jdlrobson** [tiddlyweb/tiddlywebplugins.links#2]
When exposing backlinks from other spaces in TiddlySpace e.g. viewing a tiddler foo which is linked to from a tiddler bar via [[foo]]@bar

the tiddler bar links to foo without awareness of the ControlView which restricts access in TiddlySpace

For example in:
http://jon.tiddlyspace.com/bags/jon_public/tiddlers/plugin%20meta%20markup%20for%20tiddlywiki/backlinks

the links lead to 404s.

**Comment by cdent** [comment]
actually that commit fixed #1 :(

**Comment by cdent** [comment]
fixed with some fiddling around. now space related links are handled more effectively.
