### ISSUE TITLE
json weirdness

### ISSUE THREAD

**Issue by jdlrobson** [tiddlyweb/tiddlywebplugins.links#4]
I am getting rather strange results at:
http://jon.tiddlyspace.com/bags/jon_public/tiddlers/Notes%20SPA%20for%20TiddlySpace/backlinks.json

it tells me the tiddlers are from the bag temp and also the titles are wrong - for instance I see "Notes SPA for TiddlySpace@cdent" for a tiddler who's title is actually "Notes SPA for TiddlySpace"

**Comment by cdent** [comment]
This is side effect of trying to get the HTML representation to work for both tiddlyweb and tiddlyspace, it creates some weirdness for the JSON representation. I've yet to figure out the best way to resolve it. There are conflicting goals:

 # strict correctness in the data of the tiddlers 
 # useful presentation, while still using the normal serializers

So, yeah, it's a bug, but the fix is still percolating.

**Comment by cdent** [comment]
Anyway, in the meantime, the json rep has a _canonical_uri field that you might find useful.

**Comment by jdlrobson** [comment]
Any thoughts on this?
The linkedTiddlers (http://linksocial.tiddlyspace.com)
 macro needs easy access to the real title and the real bag to work.

As a result it renders an invalid list of tiddlers.

**Comment by cdent** [comment]
I put this on my plate so it is a bit more visible to my brain. I'll get it done before I disappear.

**Comment by cdent** [comment]
How do you propose dealing with those links for which there is no tiddler, such as @jon on its own?

**Comment by cdent** [comment]
Additional information: In the tiddlyspace context the links parser and processor does _not_ know the bag. foo@jon under the hood is a pointer to foo in the recipe jon_public. That's what gets stored in the links database. So when the database is read to get front or back links it doesn't automatically know what to do. The options are:
- do a lookup then and there to resolve the bag
- not include bag in the data but do include recipe and let the client side deal

thoughs jon?

**Comment by cdent** [comment]
I've gone with the second option since chrjs can handle a bagless tiddler, using recipe instead, so there is a precedent. Gonna go ahead and install the new version and we'll see what the impact is.

**Comment by jdlrobson** [comment]
Ok.
The TiddlySpace client code is pretty built in to using server.bag for the source of a space. Imported tiddlers were now created with bag bags/null (is there anyway to exclude bag from the generated json to prevent that?)

I've updated the following code (for links) with
https://github.com/TiddlySpace/tiddlyspace/pull/693

So hopefully that will solve the problem.

**Comment by cdent** [comment]
There is no way to exclude the bag field. The fact that it is set to 'null' is supposed to be meanginful. The change in your pull is probably insufficient: It should check for bag, and use that if it is not null, then check for recipe, use that if it is not null, and bail gracefully if neither is set. All of these are possible and allowed in json collections of tiddlers.

**Comment by cdent** [comment]
In other words TiddlySpace client code needs to be better.
