### ISSUE TITLE
links only calculated for tiddlywiki text

### ISSUE THREAD

**Issue by cdent** [tiddlyweb/tiddlywebplugins.links#6]
This might be a wontfix but thought I'd throw it out there for sake of discussion (@fnd, @pads) 

Should markdown (and any other future renderer that has links) provided code to the links plugins for parsing out links for the sake of the links database?

I've not yet looked into how hard or easy this would be but the general concept that the links plugin doesn't parse, but instead looks to the renders to provide that code seems to have legs.

**Comment by FND** [comment]
Definitely yes. I hate the idea of that asymmetry, with ~~legacy~~TiddlyWiki markup being special in some way (or indeed many ways).

**Comment by pads** [comment]
+1 from me too.  I can imagine the parser looking a bit ugly if it had to handle many different formats.

**Comment by FND** [comment]
> I can imagine the parser looking a bit ugly if it had to handle many different formats

I would assume that parsing is delegated to a pluggable module based on the content type, so that shouldn't be an issue.

(I'll need to look into the implementation here to get a better sense of what the architecture looks like at the moment.)

**Comment by cdent** [comment]
A reasonable first start at this is now present from 4a1f06bd74264f7f1eb92a13078241cbe8d23c88

so closing for now
